### ISSUE TITLE
0.2.0

### ISSUE THREAD

**Issue by dennisreimann** [diy/NSStringEmojize#2]
Hey, can we have a new release with the recent additions? Thanks! :)

**Comment by dongle** [comment]
Yup - we've been tweaking the regex a bit and I think it's locked down. Will push a release this weekend!

**Comment by dennisreimann** [comment]
Thanks, that'd be great :cake:

**Comment by dongle** [comment]
updated this repo & the pod. thanks for the changes :+1:
